version: '3.1'
networks:
  projet.net:
    driver: bridge

services:
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: projet
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - projet.net

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - projet.net

  # nuxt:
  #   build:
  #     dockerfile: Dockerfile
  #   command: ["node", "/app/.output/server/index.mjs"]
  #   working_dir: /app
  #   networks:
  #     - projet.net
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #   ports:
  #     - 3000:3000